ja_user:
    resource: "@JAUserBundle/Resources/config/routing.yml"
    prefix:   /

ja_cards:
    resource: "@JACardsBundle/Resources/config/routing.yml"
    prefix:   /game

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
