ja_cards_homepage:
    path:     /
    defaults: { _controller: JACardsBundle:Default:index, name: JAde }

ja_cards_getcards:
    path:     /json/get_cards
    defaults: { _controller: JACardsBundle:CardAction:getCards }

ja_cards_checkcards:
    path:     /api/check_cards
    defaults: { _controller: JACardsBundle:CardAction:checkMoveIsLegal }
