ja_cards_game:
    path:     /play/{id}
    defaults: { _controller: JACardsBundle:Default:joinGame }

ja_cards_lobby:
    path:     /
    defaults: { _controller: JACardsBundle:Default:lobby }

ja_cards_queue:
    path:     /wait/{id}
    defaults: { _controller: JACardsBundle:Default:queue }

ja_cards_newgame:
    path:     /new
    defaults: { _controller: JACardsBundle:Default:newGame }

ja_cards_removegame:
    path:     /remove/{id}
    defaults: { _controller: JACardsBundle:Default:removeGame }
    options:
        expose: true

ja_cards_getgames:
    path:     /json/get_games
    defaults: { _controller: JACardsBundle:Default:retrieveGames }

ja_cards_getplayers:
    path:     /json/get_players
    defaults: { _controller: JACardsBundle:Default:retrievePlayers }

ja_cards_joingame:
    path:     /play/{id}
    defaults: { _controller: JACardsBundle:Default:joinGame }
ja_cards_getcards:
    path:     /json/get_cards/{id}
    defaults: { _controller: JACardsBundle:CardAction:getCards }

ja_cards_checkcards:
    path:     /api/check_cards
    defaults: { _controller: JACardsBundle:CardAction:checkMoveIsLegal }
ja_cards_ping:
    path:     /json/ping
    defaults: { _controller: JACardsBundle:CardAction:ping }