parameters:
    NomDuBundle.faye.endpoint: 'http://localhost:3000/'
    NomDuBundle.faye.adapter.class: 'Nc\FayeClient\Adapter\CurlAdapter'
    NomDuBundle.faye.client.class: 'Nc\FayeClient\Client'
 
services:
    NomDuBundle.faye.adapter:
        class: %NomDuBundle.faye.adapter.class%
 
    NomDuBundle.faye.client:
        class: %NomDuBundle.faye.client.class%
        arguments:
            - @NomDuBundle.faye.adapter
            - %NomDuBundle.faye.endpoint%